### PR TITLE
SB-46: Block Creation Via Upload

### PR DESCRIPTION
**Pull request by amortensen1229**
This PR includes...
 - removed samples from workspace
 - moved upload button from workspace to audio library
 - uploading a .wav file now create a draggable block in the audio library 
 - this block can be moved to the workspace
 - multiple blocks can be uploaded without overlapping

Video Demo:

https://user-images.githubusercontent.com/57294243/199775581-1ccac202-7640-4846-b1a1-f03ccc997f6d.mp4

### CODE REVIEW

**Comment by jeninyg** [comment]
Can you run `npx prettier --write .` for formatting?

**Comment by jeninyg** [comment]
Also, this looks really good!

**Comment by amortensen1229** [comment]
> Can you run `npx prettier --write .` for formatting?

Good call out, let me handle rn.

**Comment by amortensen1229** [comment]
Current version works running a `npm ci` followed by `npm start`.

**Pull request merged**
